
-----TABELAS-----

--Tabela JOGADOR
CREATE TABLE JOGADOR (
                         ID_JOGADOR NUMBER (30) NOT NULL,
                         NOME_JOGADOR VARCHAR2(200) NOT NULL,
                         SENHA VARCHAR2 (200) NOT NULL,
                         PRIMARY KEY (ID_JOGADOR)
);

--Sequence JOGADOR
CREATE SEQUENCE SEQ_JOGADOR
    START WITH     1
    INCREMENT BY   1
    NOCACHE
     	NOCYCLE;



--Tabela PERSONAGEM
CREATE TABLE PERSONAGEM(
                           ID_PERSONAGEM NUMBER (30) NOT NULL,
                           ID_JOGADOR NUMBER (30) NOT NULL,
                           NOME_PERSONAGEM VARCHAR2 (200) NOT NULL,
                           PRIMARY KEY (ID_PERSONAGEM)
);

--FK na tabela PERSONAGEM
ALTER TABLE PERSONAGEM
    ADD CONSTRAINT FK_JOGADOR FOREIGN KEY (ID_JOGADOR)
        REFERENCES JOGADOR(ID_JOGADOR);

--Sequence PERSONAGEM
CREATE SEQUENCE SEQ_PERSONAGEM
    START WITH     1
    INCREMENT BY   1
    NOCACHE
     	NOCYCLE;



--Tabela CLASSE_PERSONAGEM
CREATE TABLE CLASSE_PERSONAGEM(
                                  ID_CLASSE_PERSONAGEM NUMBER (30) NOT NULL,
                                  NOME_CLASSE_PERSONAGEM VARCHAR2 (200) NOT NULL,
                                  VIDA_PERSONAGEM NUMBER (30) NOT NULL,
                                  DEFESA_PERSONAGEM NUMBER (30) NOT NULL,
                                  ATAQUE_PERSONAGEM NUMBER (30) NOT NULL,
                                  ID_PERSONAGEM NUMBER (30) NOT NULL,
                                  PRIMARY KEY (ID_CLASSE_PERSONAGEM)
);

--FK na tabela CLASSE_PERSONAGEM

ALTER TABLE CLASSE_PERSONAGEM
    ADD CONSTRAINT FK_PERSONAGEM FOREIGN KEY (ID_PERSONAGEM)
        REFERENCES PERSONAGEM(ID_PERSONAGEM);

--Sequence CLASSE_PERSONAGEM
CREATE SEQUENCE SEQ_CLASSE_PERSONAGEM
    START WITH     1
    INCREMENT BY   1
    NOCACHE
     	NOCYCLE;



--Tabela CENARIO
CREATE TABLE CENARIO(
                        ID_CENARIO NUMBER (30) NOT NULL,
                        NOME_CENARIO VARCHAR2 (200) NOT NULL,
                        HORARIO DATE NOT NULL,
                        TIPO_REINO CHAR NOT NULL,
                        PRIMARY KEY (ID_CENARIO)
);

--Sequence CENARIO
CREATE SEQUENCE SEQ_CENARIO
    START WITH     1
    INCREMENT BY   1
    NOCACHE
     	NOCYCLE;



--Tabela BOSS
CREATE TABLE BOSS(
                     ID_BOSS NUMBER (30) NOT NULL,
                     NOME_BOSS VARCHAR2 (200) NOT NULL,
                     VIDA_BOSS NUMBER (30) NOT NULL,
                     DEFESA_BOSS NUMBER (30) NOT NULL,
                     ATAQUE_BOSS NUMBER (30) NOT NULL,
                     PRIMARY KEY (ID_BOSS)
);

--Sequence BOSS
CREATE SEQUENCE SEQ_BOSS
    START WITH     1
    INCREMENT BY   1
    NOCACHE
     	NOCYCLE;



--Tabela BATALHA
CREATE TABLE BATALHA(
                        ID_BATALHA NUMBER (30) NOT NULL,
                        ID_CENARIO NUMBER (30) NOT NULL,
                        ID_JOGADOR NUMBER (30) NOT NULL,
                        ID_BOSS NUMBER (30) NOT NULL,
                        ROUND_BATALHA NUMBER (30) NOT NULL,
                        STATUS VARCHAR2 (200) NOT NULL,
                        PRIMARY KEY (ID_BATALHA)
);

--FKS na tabela BATALHA

ALTER TABLE BATALHA
    ADD CONSTRAINT FK_CENARIO FOREIGN KEY (ID_CENARIO)
        REFERENCES CENARIO(ID_CENARIO);

ALTER TABLE BATALHA
    ADD CONSTRAINT FK_BOSS FOREIGN KEY (ID_BOSS)
        REFERENCES BOSS(ID_BOSS);

ALTER TABLE BATALHA
    ADD CONSTRAINT FK_JOGADOR1 FOREIGN KEY (ID_JOGADOR)
        REFERENCES JOGADOR(ID_JOGADOR);

--Sequence BATALHA
CREATE SEQUENCE SEQ_BATALHA
    START WITH     1
    INCREMENT BY   1
    NOCACHE
     	NOCYCLE;

INSERT INTO JOGADOR (ID_JOGADOR, NOME_JOGADOR , SENHA)
VALUES (SEQ_JOGADOR.nextval, 'Joao', 'Senha');

INSERT INTO PERSONAGEM (ID_PERSONAGEM, ID_JOGADOR , NOME_PERSONAGEM)
VALUES (SEQ_PERSONAGEM.nextval, 1, 'PersonagemJoao');

INSERT INTO CLASSE_PERSONAGEM (ID_CLASSE_PERSONAGEM, ID_PERSONAGEM, NOME_CLASSE_PERSONAGEM, VIDA_PERSONAGEM, DEFESA_PERSONAGEM, ATAQUE_PERSONAGEM)
VALUES (SEQ_CLASSE_PERSONAGEM.nextval, 2, 'Mago', 150, 30, 40);

INSERT INTO BOSS (ID_BOSS, NOME_BOSS, VIDA_BOSS, DEFESA_BOSS, ATAQUE_BOSS, TIPO_BOSS)
VALUES (SEQ_BOSS.nextval, 'BossSombrio', 300, 80, 40, '1');

INSERT INTO CENARIO (ID_CENARIO, NOME_CENARIO, HORARIO, TIPO_REINO)
VALUES (SEQ_CENARIO.nextval, 'ReinoSombrio',  CURRENT_DATE, '1');

INSERT INTO BATALHA (ID_BATALHA, ID_CENARIO , ID_JOGADOR , ID_BOSS , ROUND_BATALHA, STATUS)
VALUES (SEQ_BATALHA.nextval, 7, 1, 1, 6, 'Vitoria');


SELECT CURRENT_DATE FROM DUAL;

ALTER TABLE CLASSE_PERSONAGEM DROP CONSTRAINT FK_PERSONAGEM;

ALTER TABLE CLASSE_PERSONAGEM
    ADD CONSTRAINT FK_PERSONAGEM FOREIGN KEY (ID_PERSONAGEM)
        REFERENCES PERSONAGEM(ID_PERSONAGEM) ON
            DELETE
            CASCADE;

ALTER TABLE PERSONAGEM DROP CONSTRAINT FK_JOGADOR;

ALTER TABLE PERSONAGEM
    ADD CONSTRAINT FK_JOGADOR FOREIGN KEY (ID_JOGADOR)
        REFERENCES JOGADOR(ID_JOGADOR) ON
            DELETE
            CASCADE;

SELECT
    *
FROM
    PERSONAGEM;
